-- V1 — baseline schema for the SQUARE Group IT Operations Portal.
--
-- GENERATED, not hand-written: produced by Hibernate from the @Entity classes
-- (jakarta.persistence schema-generation) and verified column-for-column
-- against the live square_db — all 84 columns matched exactly.
--
-- Databases that already contained this schema before Flyway was introduced are
-- baselined at version 1 (spring.flyway.baseline-on-migrate), so this file is
-- recorded as applied without being re-run against them.
--
-- Do not edit this file. Schema changes go in a NEW file: V2__<description>.sql

create table assets (
        is_loaner boolean not null,
        loaner_issued_at date,
        original_value float(53) not null,
        purchase_date date,
        scrapped_at date,
        sent_to_repair_at date,
        useful_life_years integer not null,
        warranty_expiry date,
        id bigint generated by default as identity,
        location_id bigint,
        pending_user_id bigint,
        user_id bigint,
        asset_category varchar(255),
        asset_number varchar(255),
        department varchar(255),
        device_kind varchar(255),
        device_type varchar(255) not null,
        invoice_url varchar(255),
        ip_address varchar(255),
        pool_condition varchar(255) check ((pool_condition in ('NEW','REPAIRED','OLD_FUNCTIONAL'))),
        pr_number varchar(255),
        repair_shop varchar(255),
        scrap_reason varchar(255),
        serial_number varchar(255) not null unique,
        specifications TEXT,
        status varchar(255) not null check ((status in ('PROCURED','AVAILABLE_IN_POOL','ALLOCATED_IN_USE','UNDER_REVIEW','IN_REPAIR','VACANT_DESK','SCRAPPED'))),
        storage_location varchar(255),
        supplier_name varchar(255),
        primary key (id)
    );

    create table departments (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table import_logs (
        records_added integer not null,
        records_skipped integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        details TEXT,
        file_name varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table locations (
        floors integer not null,
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table notifications (
        due_at date,
        asset_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        employee_username varchar(255),
        message varchar(255) not null,
        status varchar(255),
        type varchar(255) not null,
        primary key (id)
    );

    create table offboarding_records (
        hold_until date,
        created_at timestamp(6),
        id bigint generated by default as identity,
        decision varchar(255) not null check ((decision in ('RETAIN_14_DAY','RELEASE_TO_IT'))),
        employee_username varchar(255) not null,
        note varchar(255),
        primary key (id)
    );

    create table tickets (
        floor integer not null,
        asset_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        resolved_at timestamp(6),
        accepted_by varchar(255),
        department varchar(255),
        description varchar(255),
        location varchar(255),
        problem_type varchar(255),
        raised_by_username varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table users (
        dob date,
        floor integer,
        joined_at date,
        offboarded boolean not null,
        id bigint generated by default as identity,
        department varchar(255),
        email varchar(255),
        employee_id varchar(255) unique,
        job_title varchar(255),
        location varchar(255),
        manager_username varchar(255),
        mobile varchar(255),
        name varchar(255),
        password varchar(255) not null,
        phone varchar(255),
        role varchar(255) not null,
        unit varchar(255),
        username varchar(255) not null unique,
        primary key (id)
    );

    create index idx_asset_serial 
       on assets (serial_number);

    create index idx_asset_status 
       on assets (status);
