-- V2 — audit trail for privileged actions.
--
-- Who reset that password, who scrapped that laptop, who changed that
-- department. Written by AuditService; never updated or deleted.

CREATE TABLE audit_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    actor_username  varchar(255) NOT NULL,
    actor_role      varchar(255),
    action          varchar(255) NOT NULL,
    target          varchar(255),
    detail          varchar(500),
    at              timestamp(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX idx_audit_at     ON audit_events (at);
CREATE INDEX idx_audit_actor  ON audit_events (actor_username);
CREATE INDEX idx_audit_action ON audit_events (action);
