-- Tenant scaffold for a future SaaS split. Adds the organizations table and a
-- nullable organization_id on the three org-scoped tables (users, assets,
-- tickets). Not enforced or populated yet — no app logic reads/writes it.
-- Seeding one default org now means a real cutover later is a backfill +
-- NOT NULL, not a schema redesign.

create table organizations (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    slug varchar(255) not null unique,
    created_at timestamp(6),
    primary key (id)
);

insert into organizations (name, slug, created_at) values ('Square Group', 'square-group', now());

alter table users add column organization_id bigint;
alter table assets add column organization_id bigint;
alter table tickets add column organization_id bigint;

alter table users add constraint fk_users_organization foreign key (organization_id) references organizations (id);
alter table assets add constraint fk_assets_organization foreign key (organization_id) references organizations (id);
alter table tickets add constraint fk_tickets_organization foreign key (organization_id) references organizations (id);
